//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignmnt
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblcity()
        {
            this.tblstuds = new HashSet<tblstud>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> stateid { get; set; }
    
        public virtual tblstate tblstate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblstud> tblstuds { get; set; }
    }
}
